version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/ci"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
