steps:
  - name: 'gcr.io/track-compliance/ci'
    id: install
    dir: dmarc_report_api
    entrypoint: pipenv
    args: ['sync', '-d', '--bare']
    env:
      - PIPENV_NOSPIN=TRUE

  - name: 'gcr.io/track-compliance/ci'
    id: test
    dir: dmarc_report_api
    entrypoint: pipenv
    args: ['run', 'test']
    env:
      - AZURE_DOMAIN=$_AZURE_DOMAIN
      - AZURE_ENDPOINT=$_AZURE_ENDPOINT
      - AZURE_KEY=$_AZURE_KEY
      - ACCOUNT=$_ACCOUNT
      - DATABASE=$_DATABASE
      - CONTAINER=$_CONTAINER
      - TOKEN=$_TOKEN
      - JWT_SECRET=$_JWT_SECRET

  - name: 'gcr.io/cloud-builders/docker'
    id: build
    dir: dmarc_report_api
    args: ['build', '-t','gcr.io/$PROJECT_ID/dmarc-report-api:$BRANCH_NAME-$SHORT_SHA', '.']

images: ['gcr.io/$PROJECT_ID/dmarc-report-api:$BRANCH_NAME-$SHORT_SHA']
